use_frameworks!

platform :ios, '8.0'

target 'TMroulette_Example' do
  pod 'TMroulette', :path => '../'

  target 'TMroulette_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
